const PRIMARY_COLOR = "#014BAA"
const SECONDARY_COLOR = "#007BFF"
const NEUTRAL_COLOR = "#BBD7EC"
const ACCENT_COLOR = "#FF9500"


export {
    PRIMARY_COLOR,
    SECONDARY_COLOR,
    NEUTRAL_COLOR,
    ACCENT_COLOR
}